// src/services/mockData.js
// All mock data in one place — swap for real API later

export const MOCK_USER = {
  id: 'user_001',
  fullName: 'Sarah Johnson',
  email: 'sarah@email.com',
  avatarUrl: null,
  memberSince: 'May 2024',
  stats: {
    questsCompleted: 12,
    co2Saved: '24kg',
    badgesEarned: 8,
  },
};

export const MOCK_QUESTS = [
  {
    id: 'quest_001',
    title: 'Bring your reusable cup',
    description: 'Help reduce waste by bringing your own cup for any hot drink.',
    businessName: 'Green Leaf Café',
    businessLogo: null,
    category: 'eco',
    distance: '0.2 km',
    reward: {
      amount: 200, // pence
      credits: 50,
      label: '£2.00',
    },
    steps: [
      { id: 1, instruction: 'Bring your reusable cup', completed: false },
      { id: 2, instruction: 'Order any hot drink', completed: false },
      { id: 3, instruction: 'Scan the QR code at the counter', completed: false },
    ],
    totalSteps: 3,
    imageUrl: null,
    isSponsored: true,
    sponsoredBy: 'Green Leaf Café',
    tags: ['Reusable Cup Friendly', 'Local Business'],
  },
  {
    id: 'quest_002',
    title: 'Zero Waste Challenge',
    description: 'Spend £10 or more at Zero Waste Shop and get rewarded.',
    businessName: 'Zero Waste Shop',
    businessLogo: null,
    category: 'zero-waste',
    distance: '0.5 km',
    reward: {
      amount: 0,
      credits: 60,
      label: '+60',
    },
    steps: [
      { id: 1, instruction: 'Visit Zero Waste Shop', completed: false },
      { id: 2, instruction: 'Spend £10 or more', completed: false },
      { id: 3, instruction: 'Scan the QR code', completed: false },
    ],
    totalSteps: 3,
    imageUrl: null,
    isSponsored: false,
    tags: ['Zero Waste'],
  },
  {
    id: 'quest_003',
    title: 'Refill & Save',
    description: 'Refill any bottle at our station and save plastic.',
    businessName: 'Refill Station',
    businessLogo: null,
    category: 'refill',
    distance: '0.8 km',
    reward: {
      amount: 0,
      credits: 30,
      label: '+30',
    },
    steps: [
      { id: 1, instruction: 'Bring any bottle', completed: false },
      { id: 2, instruction: 'Use the refill station', completed: false },
    ],
    totalSteps: 2,
    imageUrl: null,
    isSponsored: false,
    tags: ['Plastic Free'],
  },
  {
    id: 'quest_004',
    title: 'Meatless Monday',
    description: 'Order a plant-based meal every Monday.',
    businessName: 'Green Bites',
    businessLogo: null,
    category: 'food',
    distance: '0.7 km',
    reward: {
      amount: 0,
      credits: 40,
      label: '+40',
    },
    steps: [
      { id: 1, instruction: 'Visit Green Bites on a Monday', completed: false },
      { id: 2, instruction: 'Order any plant-based dish', completed: false },
      { id: 3, instruction: 'Scan the QR code', completed: false },
    ],
    totalSteps: 3,
    imageUrl: null,
    isSponsored: false,
    tags: ['Plant-Based'],
  },
  {
    id: 'quest_005',
    title: 'Walk & Earn',
    description: 'Walk 5,000 steps and earn rewards.',
    businessName: 'CityFit',
    businessLogo: null,
    category: 'fitness',
    distance: '1.2 km',
    reward: {
      amount: 0,
      credits: 25,
      label: '+25',
    },
    steps: [
      { id: 1, instruction: 'Walk 5,000 steps today', completed: false },
      { id: 2, instruction: 'Sync your steps in the app', completed: false },
    ],
    totalSteps: 2,
    imageUrl: null,
    isSponsored: false,
    tags: ['Fitness', 'Wellbeing'],
  },
];

export const MOCK_ACTIVITY_HISTORY = [
  {
    id: 'activity_001',
    questTitle: 'Bring your reusable cup',
    businessName: 'Green Leaf Café',
    date: 'May 20, 2024 at 10:32 AM',
    reward: { amount: 200, credits: 50, label: '+£2.00' },
    status: 'Completed',
    type: 'Quest',
    paymentMethod: 'Wallet Balance',
    month: 'May 2024',
  },
  {
    id: 'activity_002',
    questTitle: 'Zero Waste Challenge',
    businessName: 'Zero Waste Shop',
    date: 'May 18, 2024',
    reward: { amount: 200, credits: 60, label: '+£2.00' },
    status: 'Completed',
    type: 'Quest',
    paymentMethod: 'Wallet Balance',
    month: 'May 2024',
  },
  {
    id: 'activity_003',
    questTitle: 'Refill & Save',
    businessName: 'Refill Station',
    date: 'May 13, 2024',
    reward: { amount: 30, credits: 30, label: '+£0.30' },
    status: 'Completed',
    type: 'Quest',
    paymentMethod: 'Wallet Balance',
    month: 'May 2024',
  },
  {
    id: 'activity_004',
    questTitle: 'Meatless Monday',
    businessName: 'Green Bites',
    date: 'May 13, 2024',
    reward: { amount: 40, credits: 40, label: '+£0.40' },
    status: 'Completed',
    type: 'Quest',
    paymentMethod: 'Wallet Balance',
    month: 'May 2024',
  },
  {
    id: 'activity_005',
    questTitle: 'Walk & Earn',
    businessName: 'CityFit',
    date: 'May 13, 2024',
    reward: { amount: 25, credits: 25, label: '+£0.25' },
    status: 'Completed',
    type: 'Quest',
    paymentMethod: 'Wallet Balance',
    month: 'May 2024',
  },
  {
    id: 'activity_006',
    questTitle: 'Weekend Special',
    businessName: 'Green Leaf Café',
    date: 'Apr 26, 2024',
    reward: { amount: 200, credits: 50, label: '+£2.00' },
    status: 'Completed',
    type: 'Quest',
    paymentMethod: 'Wallet Balance',
    month: 'April 2024',
  },
];

export const MOCK_REDEEM_OFFERS = [
  {
    id: 'offer_001',
    title: '10% off at Green Leaf Café',
    businessName: 'Green Leaf Café',
    discount: '10%',
    badgeLabel: '10% OFF',
    minSpend: 5,
    color: '#1A4731',
  },
  {
    id: 'offer_002',
    title: '£5 off at Zero Waste Shop',
    businessName: 'Zero Waste Shop',
    discount: '£5 OFF',
    badgeLabel: '£5 OFF',
    minSpend: 20,
    color: '#0D9488',
  },
  {
    id: 'offer_003',
    title: 'Free refill at Refill Station',
    businessName: 'Refill Station',
    discount: 'FREE',
    badgeLabel: 'FREE',
    minSpend: 0,
    limitPerDay: 1,
    color: '#2563EB',
  },
];

export const MOCK_SAVED_PLACES = [
  {
    id: 'place_001',
    name: 'Green Leaf Café',
    category: 'Café',
    distance: '0.2 km',
    rating: 4.8,
    reviewCount: 230,
    address: '12 Green St, London, UK',
    hours: 'Open · Closes 8:00 PM',
    description: 'Cosy neighbourhood café serving delicious coffee with a sustainable mindset.',
    imageUrl: null,
    tags: ['Reusable Cup Friendly', 'Local Business'],
    activeQuests: ['quest_001'],
  },
  {
    id: 'place_002',
    name: 'Zero Waste Shop',
    category: 'Sustainable Store',
    distance: '0.4 km',
    rating: 4.6,
    reviewCount: 180,
    address: '45 Eco Lane, London, UK',
    hours: 'Open · Closes 7:00 PM',
    description: 'The UK\'s leading zero-waste refill shop.',
    imageUrl: null,
    tags: ['Zero Waste', 'Plastic Free'],
    activeQuests: ['quest_002'],
  },
  {
    id: 'place_003',
    name: 'Refill Station',
    category: 'Water Refill',
    distance: '0.5 km',
    rating: 4.4,
    reviewCount: 95,
    address: '7 Blue St, London, UK',
    hours: 'Open 24 hours',
    description: 'Free water refill station — save plastic every day.',
    imageUrl: null,
    tags: ['Plastic Free', 'Free'],
    activeQuests: ['quest_003'],
  },
  {
    id: 'place_004',
    name: 'Green Bites',
    category: 'Healthy Food',
    distance: '0.7 km',
    rating: 4.5,
    reviewCount: 210,
    address: '88 Plant Rd, London, UK',
    hours: 'Open · Closes 9:00 PM',
    description: 'Delicious plant-based meals for a healthier planet.',
    imageUrl: null,
    tags: ['Plant-Based', 'Vegan Friendly'],
    activeQuests: ['quest_004'],
  },
  {
    id: 'place_005',
    name: 'CityFit Studio',
    category: 'Fitness',
    distance: '1.2 km',
    rating: 4.7,
    reviewCount: 340,
    address: '22 Active Ave, London, UK',
    hours: 'Open · Closes 10:00 PM',
    description: 'Modern fitness studio encouraging active sustainable lifestyles.',
    imageUrl: null,
    tags: ['Fitness', 'Wellbeing'],
    activeQuests: ['quest_005'],
  },
];

export const MOCK_PAYMENT_METHODS = [
  {
    id: 'pm_001',
    type: 'card',
    brand: 'visa',
    last4: '4242',
    expiry: '13/26',
    name: 'Sarah Johnson',
    isDefault: true,
  },
  {
    id: 'pm_002',
    type: 'card',
    brand: 'mastercard',
    last4: '8888',
    expiry: '09/25',
    name: 'Sarah Johnson',
    isDefault: false,
  },
  {
    id: 'pm_003',
    type: 'paypal',
    email: 'sarah.johnson@email.com',
    isDefault: false,
  },
  {
    id: 'pm_004',
    type: 'apple_pay',
    isDefault: false,
  },
];

export const MOCK_FAQ = [
  { id: 'faq_001', question: 'How do quests work?', category: ['Popular', 'Quests'] },
  { id: 'faq_002', question: 'How do I earn rewards?', category: ['Popular', 'Rewards'] },
  { id: 'faq_003', question: 'How do I submit proof?', category: ['Popular', 'Quests'] },
  { id: 'faq_004', question: 'When will I receive my reward?', category: ['Popular', 'Rewards'] },
  { id: 'faq_005', question: 'What are Green Credits?', category: ['Popular', 'Rewards'] },
  { id: 'faq_006', question: 'How do I invite a friend?', category: ['Popular', 'Account'] },
  { id: 'faq_007', question: 'How do I change my email?', category: ['Account'] },
  { id: 'faq_008', question: 'How do I delete my account?', category: ['Account'] },
];

export const MOCK_MAP_LOCATIONS = [
  { id: 'map_001', placeId: 'place_001', latitude: 51.5074, longitude: -0.1278, name: 'Green Leaf Café' },
  { id: 'map_002', placeId: 'place_002', latitude: 51.5080, longitude: -0.1260, name: 'Zero Waste Shop' },
  { id: 'map_003', placeId: 'place_003', latitude: 51.5060, longitude: -0.1300, name: 'Refill Station' },
  { id: 'map_004', placeId: 'place_004', latitude: 51.5090, longitude: -0.1240, name: 'Green Bites' },
  { id: 'map_005', placeId: 'place_005', latitude: 51.5050, longitude: -0.1310, name: 'CityFit Studio' },
];
